### ISSUE TITLE
Register UCSD uploaded data against multiple datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#1]
Organize the data in each directory under 
/hive/hubmap/data/consortium/Kharchenko_Processed_SNARE/* to have a new dataset with source datasets (multiple sources for each new dataset) for all of the corresponding collection (first column in spreadsheet linked below) and data type accessible chromatin (_AC) and RNA (_R) (characters after SNARE2 in the second column in the spreadsheet linked below).

Spreadsheet:  https://docs.google.com/spreadsheets/d/1gl6T1oCP0pjt1RUBBiIgsW6fvSL5IxOM/edit#gid=1588971180

**Comment by shirey** [comment]
@cborromeo   Per our conversation, you'll create 8 new datasets attached as a derived dataset to the first one in each group with the names that follow with an "other" data type of either snare_ac or snare_rna.  Then, you will manually attach the new derived dataset to the other source datasets.  

New derived dataset names:
BUKMAP_20190529D_SNARE2_AC
BUKMAP_20190529E_SNARE2_AC
BUKMAP_20190529F_SNARE2_AC
BUKMAP_20190529G_SNARE2_AC
BUKMAP_20190529D_SNARE2_RNA
BUKMAP_20190529E_SNARE2_RNA
BUKMAP_20190529F_SNARE2_RNA
BUKMAP_20190529G_SNARE2_RNA

**Comment by cborromeo** [comment]
The following curl command will accomplish this task.  I will use a variant of it on PROD:

**Comment by cborromeo** [comment]
This was completed in PROD.  Here are the resulting datasets:

[Reorg_UCSD_SNARE_seq_data.xlsx](https://github.com/hubmapconsortium/manual-data-ingest/files/5132371/Reorg_UCSD_SNARE_seq_data.xlsx)
