### ISSUE TITLE
Deletion of datasets

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/manual-data-ingest#100]
There are three test uploads that can be deleted from the ingest portal:

- HBM745.QMQK.797 (6d094503393d6d41b6193c9d10e33d9e)
- HBM536.PGMQ.634 (77bee25927617a84a5cf802e33c9efb2)
- HBM685.QTKB.264 (ba7f3486686a10d8969969ac5f44a755)

Thanks,
Brendan

**Comment by bhonick** [comment]
@shirey Here are some further datasets to be deleted:

	- HBM935.BPGJ.466
	- HBM293.DNNM.454
	- HBM864.WFRW.547

Thanks!

**Comment by shirey** [comment]
@bhonick If I delete all of the above datasets the following processed datasets will need to be deleted as well because they'll be orphaned in the provenance graph (the primary dataset that they are associated with will be deleted).  Please confirm that it is okay to delete them:
```
HBM427.JDGV.725
HBM247.FNTF.884
HBM689.JJVV.243
HBM433.XFNR.595
HBM958.XMXW.797
HBM227.RDMB.255
HBM958.NRDJ.459
```

**Comment by bhonick** [comment]
Thanks @shirey ! Yes, those processed datasets can be deleted.

**Comment by shirey** [comment]
These have been deleted.
