### ISSUE TITLE
Publish Northwestern LC-MS data

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#105]
Per email from Peter on Thursday, July 7 @ 1:38 publish the following datasets:
```
HBM648.QVGL.995
HBM247.LBFP.935
HBM857.DKPM.277
HBM348.TWWB.352
HBM446.BSSN.562
HBM755.LRFS.688
HBM984.PSPF.676
HBM232.VMCT.877
HBM454.FVCQ.632
HBM454.BNCC.556
```

**Comment by shirey** [comment]
Confirmed that the datasets are in QA state and have associated Donor (metadata).  Most datasets have associated Sample (meta)data, but two datasets need associated Sample (meta)data:
```
HBM857.DKPM.277
HBM348.TWWB.352
```
It looks like they got the tissue from Florida and UCSD and processed at Northwestern?  The associated tissue samples where we could attach metadata to are:
```
HBM857.DKPM.277 -> UFL0003-SP-2/ HBM434.GPCX.452 (tissue from Florida)
HBM348.TWWB.352 -> UCSD0015-RL-8/HBM466.CDSN.556 (tissue from UCSD)
```

**Comment by pecan88** [comment]
HBM857.DKPM.277 has donor data and Alan has abstracted it.  It now needs to be loaded by the dev team.

[HBM348.TWWB.352 appears to have donor data loaded on the Portal](https://portal.hubmapconsortium.org/browse/donor/4397fcd072ac96299992b47da1dbae64), however I can't confirm whether we've loaded all that was abstracted by Jonathan or Alan.  @AlanSimmons  can you confirm?

**Comment by AlanSimmons** [comment]
Short answer: probably, but I can't confirm.

Longer answer:
This was abstracted back in March, so it would have been @computationdoc. 

The Data Portal shows that the patient has most of the clinical metadata that we can currently display. The only thing that is missing is the KDPI.

I cannot find source files in the "HubMAP Protected Data  - University Pittsburgh" that correspond to a donor ID UCSD-0015.

**Comment by shirey** [comment]
@pecan88 These data have been published.

**Comment by pecan88** [comment]
@shirey  

![image](https://user-images.githubusercontent.com/21177919/188941735-81bc5248-d0f6-4811-b025-620ba3a814c3.png)

It appears the following two were not published (listed in QA)

HBM755.LRFS.688
HBM247.LBFP.935

**Comment by shirey** [comment]
@pecan88 Everything was correct in our database (they are actually published), but for some reason the indices that drive the Data Portal weren't synchronized with the db.  I sent a call for each of the incorrectly displayed datasets to sync, please check again and close this if they are now published in the Portal.
