### ISSUE TITLE
Publish UFL CODEX data

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#106]
Per email from Peter on June 23 @ 11:38 publish the following datasets:

```
HBM535.GGVZ.446
HBM452.ZQFK.527
HBM783.JZRN.564
HBM687.CWVH.758
HBM443.TZCQ.232
HBM659.XHFH.996
HBM327.NMZP.779
HBM374.LLKS.325
HBM287.WDKX.539
HBM882.DBTR.869
HBM387.QZQF.984
HBM543.RSRV.265
HBM673.TNZM.339
HBM283.GNGR.785
HBM483.KDBW.482
HBM632.JSNP.578
HBM792.GKBV.697
HBM979.JTRM.429
HBM892.HBJW.994
HBM455.XDQS.993
HBM594.PWXG.764
HBM724.PJNC.827
HBM967.TGDD.996
HBM968.CJLB.479
HBM548.TSMP.663
HBM455.PWQW.883
HBM443.FDHZ.888
HBM498.TCSV.345
HBM457.JZFF.434
HBM989.VVXT.224
```

**Comment by shirey** [comment]
Most data did not have associated Donor metadata, the following did so were published.  The remaining will be published when the donor metadata has been imported.  Published:
```
  HBM548.TSMP.663
  HBM968.CJLB.479
  HBM724.PJNC.827
  HBM967.TGDD.996
  HBM594.PWXG.764
  HBM455.XDQS.993
  HBM989.VVXT.224
```

We need donor metadata for:
```
  UFL0010/HBM338.KSBT.288
  UFL0011/HBM637.QBTV.856
  UFL0012/HBM643.RGRZ.429
  UFL0013/HBM723.NSQV.587
  UFL0014/HBM437.HTCQ.742
  UFL0015/HBM994.TNMH.444
```

**Comment by pecan88** [comment]
@computationdoc  - any update on sharing the donor data associated with UFL CODEX datasets?

**Comment by AlanSimmons** [comment]
Abstracted data on the following donors:
UFL0010 / HBM338.KSBT.288
  UFL0011 / HBM637.QBTV.856
  UFL0012 / HBM643.RGRZ.429
  UFL0013 / HBM723.NSQV.587
  UFL0014 / HBM437.HTCQ.742
  UFL0015 / HBM994.TNMH.444

**Comment by pecan88** [comment]
Reminder re: loading donor data to support Florida submissions.

**Comment by AlanSimmons** [comment]
Data for these donors has been abstracted and ingested. However, there appear to be data quality issues in the displayed metadata. For example, the race is showing as "Race", although the input spreadsheets code for a race. In addition, HBM994.TNMH.444 shows a field 

finding_by_cause | Cause of Death, Mechanism of Injury, Circumstances of Death

instead of three fields for cause of death, mechanism of injury, and circumstances of death.

**Comment by pecan88** [comment]
Hmm - have you shared back with Florida site?  What can I do to help?

**Comment by AlanSimmons** [comment]
Clinical data for donors have been re-abstracted and are ready for ingestion:
UFL0010 / HBM338.KSBT.288
UFL0011 / HBM637.QBTV.856
UFL0012 / HBM643.RGRZ.429
UFL0013 / HBM723.NSQV.587
UFL0014 / HBM437.HTCQ.742
UFL0015 / HBM994.TNMH.444

**Comment by pecan88** [comment]
@shirey - when would we plan targeting the load of this donor data?

**Comment by pecan88** [comment]
@shirey & @AlanSimmons - it sounds like we have abstracted the Florida donor data for the blocked datasets above.  Do we need anything else from Florida prior to our requesting publication of the datasets?

**Comment by AlanSimmons** [comment]
@pecan88 Donor data has been ingested into HuBMAP. I just confirmed that the donors show metadata. I think that this is complete.

**Comment by shirey** [comment]
@pecan88 HBM535.GGVZ.446 was deleted per a message from Brendan-- not sure why it was originally slated for publication.
