### ISSUE TITLE
Deletion of datasets

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/manual-data-ingest#109]
@shirey The following datasets can be deleted:

	- HBM524.VDVF.848
	- HBM269.TSPP.362
	- HBM372.CFKC.479
	- HBM697.ZHHQ.856

Thanks!

**Comment by bhonick** [comment]
@shirey Adding some more datasets to be deleted, thanks!

	- HBM599.JBRG.559
	- HBM573.HQBT.893
	- HBM973.NRHW.279
	- HBM333.PBQD.982
	- HBM768.QRTX.295
	- HBM649.LVSX.553
	- HBM279.LJLB.643
	- HBM584.KLKC.965
	- HBM693.XJQN.442

**Comment by bhonick** [comment]
@shirey Adding some additional datasets to be deleted, thanks!

	- HBM485.ZBWG.746
	- HBM735.VJCQ.257
	- HBM989.FKRV.474
	- HBM983.HMCS.593
	- HBM228.PBWM.539
	- HBM439.LFPD.344
	- HBM375.LKFR.426
	- HBM224.BGRW.363
	- HBM442.HBHG.858
	- HBM393.JHQC.762
	- HBM853.NQWK.292
	- HBM376.PPWD.224
	- HBM847.GJHG.824
	- HBM558.NNXZ.728

**Comment by bhonick** [comment]
@shirey Here is another dataset that can be deleted, thanks!

-HBM489.ZVNR.345

**Comment by bhonick** [comment]
@shirey here are some more datasets to be deleted, thanks!

	- HBM656.TJNG.945 - In QA state, but has been replaced due to a metadata problem
	- HBM526.BXJR.935 - Errored
	- HBM262.NJQZ.634 - Still in Processing state because I cancelled its processing in Airflow

**Comment by shirey** [comment]
@bhonick A few issues:

  - Dataset  HBM524.VDVF.848 has processed dataset HBM544.VXZT.422 in QA state associated with it and
  - Dataset  HBM697.ZHHQ.856 has processed dataset HBM597.CGBS.977 in QA state associated
What should be done with these processed datasets?
  
  Beyond the dataset that you list above in QA the following two sets are also in QA, please confirm that they should be deleted 
  - HBM524.VDVF.848
  - HBM697.ZHHQ.856

**Comment by bhonick** [comment]
Hi, @shirey, I confirm that those primary and derived datasets can be deleted. I received a request from the data provider stating that they've been superseded by the contents of the higher-quality upload HBM497.HXGH.988). Thanks!

**Comment by pecan88** [comment]
Reminder / nudge to @shirey re: deletion / clean up of datasets here.  It'd be great if we could remove them so that reporting is clearer and so that certain data providers don't keep asking us about it ... :)

**Comment by bhonick** [comment]
@shirey Submitting a derived dataset in QA stage for deletion (has incorrect visualization and has been replaced by a newer derived dataset): 

HBM986.TVWZ.364

**Comment by pecan88** [comment]
Two additional datasets flagged for deletion, approved by BL of UCSD:

HBM358.LRJG.425
HBM748.TBBX.547

**Comment by bhonick** [comment]
@shirey Here are some additional datasets for deletion (all are MALDI IMS in QA, but we have authorization from the data provider):

	- HBM599.RZXH.996
	- HBM424.ZFRH.757
	- HBM586.DDJP.354
	- HBM452.XNQD.984
	- HBM592.CDFP.566
	- HBM892.XKJD.345
	- HBM773.QBBS.536
	- HBM666.LSVF.433
	- HBM783.BQTQ.572
	- HBM354.SVRR.453
	- HBM234.KMKH.686
	- HBM645.HLXR.825
	- HBM393.FBWL.474
	- HBM585.SPHC.855
	- HBM392.WMMN.248
	- HBM443.NMPG.363
	- HBM833.KTHB.422
	- HBM998.BFKQ.983
	- HBM943.MSQJ.634
	- HBM895.CWNL.437
	- HBM996.BKTN.654
	- HBM775.DGJB.823
	- HBM495.DRKN.757
	- HBM245.PZPB.787
	- HBM558.XRGS.273
	- HBM455.NPSX.655
	- HBM592.XSHL.887
	- HBM286.XWSF.876

**Comment by pecan88** [comment]
Datasets requested to be deleted by Stanford ... sent a while back by Chris Briggs.
HBM977.PCGP.852
HBM528.JRCM.382
HBM473.WPPC.778
HBM382.ZFZR.675
HBM775.ZQHP.696
HBM724.SCXJ.259

**Comment by bhonick** [comment]
@shirey Sounds good! There should be no problem in deleting those derived datasets if we are getting rid of the primaries.

**Comment by shirey** [comment]
This is done.  90 total datasets deleted.

**Comment by bhonick** [comment]
Thank you very much! @shirey
