### ISSUE TITLE
Editing number_of_antibodies in neo4j for Stanford CODEX

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/manual-data-ingest#112]
Hi @shirey, could you edit some values in neo4j for number_of_antibodies for a couple of Stanford CODEX primary datasets? I talked to Joel about this, and he said having you change them would be the best approach. Below is the list (all of the primaries have a value of 69 for number_of_datasets, and that needs to be changed to 57). Thanks!

- HBM439.WJDV.974
- HBM845.VMSZ.536
- HBM683.NRPR.962
- HBM438.JXJW.249
- HBM727.DMKG.675
- HBM666.RBCG.529
- HBM353.NZVQ.793
- HBM785.FJVT.469

**Comment by pecan88** [comment]
@shirey - just checking in re: status and potential ETA.  Thank you for loading into the sprint, sir.  :)
