### ISSUE TITLE
Deletion of Donors (and associated samples)

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/manual-data-ingest#118]
@shirey Can you delete the following donors and any associated samples? I checked the portal, and there aren't any datasets linked to these donors.

Thanks!

HBM437.HSZM.576
HBM546.SFGS.958
HBM933.LDXP.844
HBM988.TKXC.696
HBM262.WCTP.479
HBM587.TSTM.685
HBM364.FWSK.353
HBM222.PGNH.299

**Comment by shirey** [comment]
@bhonick Just to clarify- I think there are Sample registrations attached to these Donors as well, so will need to be deleted too.

**Comment by shirey** [comment]
@bhonick, no need- I can generate.

**Comment by shirey** [comment]
@bhonick These were deleted, including these samples:

"98d05f3e70cbdfba8aeae13385b1265c"
"ec3f2cd6a646ada16dffc22f76fc2d5e"
"550acb9c2f835546ef89684ab8992e01"
"b65f04bbebc67bd4fa7508797e77d016"
"f49fe260dabfb01852c06ac83a3e197d"
"f6234210eaaa485ce91a6e61cdeb60dc"
"a439fe31764445f278739e7eeed3b1c4"
"ad4e33d25632441a2e2706ffb5667f2f"
"1f4caa3b8e313aa975cdbea439072df8"
"817b7bed990c9c50965cf1ae648a1f1e"
"ca795a462fbb243d0eed0cd265666ecb"

**Comment by bhonick** [comment]
Thanks!
