### ISSUE TITLE
Create a Collection for Kaggle competition datasets.

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#12]
Create a Collection to organize the datasets involved in the Kaggle compitition.

**Comment by shirey** [comment]
The contributor/contact info is in this file:

[kaggle_contributers.tsv.txt](https://github.com/hubmapconsortium/manual-data-ingest/files/6496490/kaggle_contributers.tsv.txt)

**Comment by khanshawPSC** [comment]
Title: HuBMAP "Hacking the Kidney" 2021 Kaggle Competition Dataset - Glomerulus Segmentation on Periodic acid-Schiff Whole Slide Images

**Comment by khanshawPSC** [comment]
Description:
Our best estimates show there are over 7 billion people on the planet and 300 billion stars in the Milky Way galaxy. By comparison, the adult human body contains 37 trillion cells. To determine the function and relationship among these cells is a monumental undertaking. Many areas of human health would be impacted if we better understand cellular activity. A problem with this much data is a great match for the Kaggle community.

Just as the Human Genome Project mapped the entirety of human DNA, the Human BioMolecular Atlas Program (HuBMAP) is a major endeavor. Sponsored by the National Institutes of Health (NIH), HuBMAP is working to catalyze the development of a framework for mapping the human body at a level of glomerulus functional tissue units for the first time in history. Hoping to become one of the world’s largest collaborative biological projects, HuBMAP aims to be an open map of the human body at the cellular level.

The competitions challenge is to detect glomerulus functional tissue units (FTUs) across different tissue preparation pipelines. An FTU is defined as a “three-dimensional block of cells centered around a capillary, such that each cell in this block is within diffusion distance from any other cell in the same block” (de Bono, 2013). The goal of this competition is the implementation of a successful and robust glomeruli FTU detector.

Advancements in HuBMAP will accelerate the world’s understanding of the relationships between cell and tissue organization and function and human health. These datasets and insights can be used by researchers in cell and tissue anatomy, pharmaceutical companies to develop therapies, or even parents to show their children the magnitude of the human body.

**Comment by khanshawPSC** [comment]
hubmap ids:

HBM875.QHDJ.259
HBM463.JRTB.582
HBM958.GHFM.676
HBM636.ZPTS.368
HBM725.PDDC.788
HBM636.GVWP.354
HBM362.PTQJ.743
HBM783.GDKK.879
HBM389.MBWW.346
HBM879.CDHB.995
HBM662.PMPZ.644
HBM833.DBGG.252
HBM473.FKKH.583
HBM874.RZDW.757
HBM849.XMPC.398
HBM623.RPMC.638
HBM979.HDZH.896
HBM276.PGFS.693
HBM264.XSVF.528
HBM676.SNVK.793
HBM984.PMZN.942
HBM649.XFQG.775
HBM627.RSGW.898
HBM344.LLLV.539
HBM296.RLWW.755
HBM324.ZGZM.874
HBM673.JJRZ.435
HBM227.THVC.544
HBM649.DLZF.463
HBM832.FQKR.463
