### ISSUE TITLE
Deletion of Datasets

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/manual-data-ingest#130]
@shirey These datasets can be deleted:

1.	HBM978.SKJK.457
2.	HBM443.RVPF.723
3.	HBM564.VFQF.445
4.	HBM325.NFQN.958
5.	HBM374.LXZR.573
6.	HBM356.HJJX.599
7.	HBM572.SFFK.265
8.	HBM743.NKZJ.966
9.	HBM286.SXPW.464
10.	HBM693.TKSR.989
11.	HBM532.BHTS.856
12.	HBM329.LFSX.674
13.	HBM397.DHFQ.274
14.	HBM932.CWJK.484
15.	HBM443.PTSG.997
16.	HBM932.NDPL.855
17.	HBM293.WGGB.527
18.	HBM947.LJKB.895
19.	HBM626.DQGW.649
20.	HBM242.QRZL.845
21.	HBM752.MJJP.255
22.	HBM946.LXHD.342
23.	HBM359.WSTS.688
24.	HBM342.FWKM.533
25.	HBM874.KPCK.377
26.	HBM566.FZMF.395
27.	HBM827.MTPX.728
28.	HBM796.MHMH.858
29.	HBM922.GQCQ.878
30.	HBM688.VFBR.562
31.	HBM654.JKBH.876
32.	HBM638.GQKL.939
33.	HBM228.FHZX.327
34.	HBM635.BVKS.668
35.	HBM828.CWHW.846
36.	HBM277.LMNX.958
37.	HBM359.MJQR.358
38.	HBM554.FXRG.494
39.	HBM998.SRDK.623
40.	HBM436.MSWB.224
41.	HBM246.HHVD.268
42.	HBM796.RCLG.449
43.	HBM498.GZWT.752
44.	HBM359.TNQB.955
45.	HBM783.GTZQ.328
46.	HBM348.NMWC.895
47.	HBM569.GNMW.442
48.	HBM826.JWQZ.557
49.	HBM286.BTKN.227
50.	HBM979.DRXV.239
51.	HBM435.XZDT.895
52.	HBM756.ZBJS.464
53.	HBM846.GNFK.382
54.	HBM828.MQHS.633
55.	HBM266.VHFM.835

**Comment by shirey** [comment]
@bhonick The following datasets contain associated processed data, please confirm that this data should be deleted too-- of note, not all processed data is in the "Error" state, but in "QA"

ds.hubmap_id	ds.status	processed.hubmap_id	processed.status
"HBM569.GNMW.442"	"New"	"HBM929.MWVM.268"	"Error"
"HBM569.GNMW.442"	"New"	"HBM382.VPBX.866"	"Error"
"HBM564.VFQF.445"	"New"	"HBM836.GLRK.587"	"Error"
"HBM286.SXPW.464"	"New"	"HBM925.HRDD.244"	"Error"
"HBM443.PTSG.997"	"New"	"HBM657.STHT.488"	"Error"
"HBM752.MJJP.255"	"New"	"HBM428.FCTJ.655"	"Error"
"HBM932.NDPL.855"	"New"	"HBM343.SWZV.994"	"Error"
"HBM946.LXHD.342"	"New"	"HBM957.NZZF.862"	"Error"
"HBM693.TKSR.989"	"New"	"HBM258.PBVL.874"	"Error"
"HBM325.NFQN.958"	"New"	"HBM749.GDWW.698"	"Error"
"HBM846.GNFK.382"	"New"	"HBM359.RDNH.724"	"Error"
"HBM826.JWQZ.557"	"New"	"HBM277.WPRB.277"	"Error"
"HBM498.GZWT.752"	"New"	"HBM577.FZTG.357"	"Error"
"HBM554.FXRG.494"	"New"	"HBM274.JZBC.499"	"Error"
"HBM554.FXRG.494"	"New"	"HBM894.JSZG.933"	"Error"
"HBM827.MTPX.728"	"New"	"HBM883.XVPB.363"	"Error"
"HBM828.MQHS.633"	"New"	"HBM538.KWLQ.343"	"Error"
"HBM286.BTKN.227"	"New"	"HBM578.BPWC.352"	"Error"
"HBM635.BVKS.668"	"New"	"HBM569.MGWP.595"	"Error"
"HBM998.SRDK.623"	"New"	"HBM563.WZNS.796"	"Error"
"HBM374.LXZR.573"	"New"	"HBM697.NHWT.586"	"Error"
"HBM359.TNQB.955"	"New"	"HBM768.DPJW.762"	"Error"
"HBM796.MHMH.858"	"New"	"HBM338.TWMK.388"	"Error"
"HBM532.BHTS.856"	"New"	"HBM644.FMMQ.355"	"Error"
"HBM293.WGGB.527"	"New"	"HBM282.CPCL.237"	"Error"
"HBM359.WSTS.688"	"New"	"HBM677.PDZZ.373"	"Error"
"HBM922.GQCQ.878"	"New"	"HBM689.BRLJ.478"	"Error"
"HBM828.CWHW.846"	"New"	"HBM224.KJRP.363"	"Error"
"HBM654.JKBH.876"	"New"	"HBM444.DXTZ.962"	"Error"
"HBM436.MSWB.224"	"QA"	"HBM935.GXNP.963"	"QA"
"HBM436.MSWB.224"	"QA"	"HBM957.LBVT.224"	"QA"
"HBM783.GTZQ.328"	"QA"	"HBM849.KCSB.536"	"QA"
"HBM979.DRXV.239"	"QA"	"HBM839.ZFRD.789"	"QA"
"HBM266.VHFM.835"	"QA"	"HBM523.BXZM.965"	"QA"
"HBM356.HJJX.599"	"QA"	"HBM685.MSCQ.978"	"QA"
"HBM329.LFSX.674"	"QA"	"HBM876.ZBTD.373"	"QA"
"HBM329.LFSX.674"	"QA"	"HBM249.BHHN.863"	"QA"
"HBM947.LJKB.895"	"QA"	"HBM265.NQCH.947"	"QA"
"HBM342.FWKM.533"	"QA"	"HBM536.FHLK.529"	"QA"
"HBM688.VFBR.562"	"QA"	"HBM388.BLRJ.658"	"QA"ds.hubmap_id	ds.status	processed.hubmap_id	processed.status
"HBM569.GNMW.442"	"New"	"HBM929.MWVM.268"	"Error"
"HBM569.GNMW.442"	"New"	"HBM382.VPBX.866"	"Error"
"HBM564.VFQF.445"	"New"	"HBM836.GLRK.587"	"Error"
"HBM286.SXPW.464"	"New"	"HBM925.HRDD.244"	"Error"
"HBM443.PTSG.997"	"New"	"HBM657.STHT.488"	"Error"
"HBM752.MJJP.255"	"New"	"HBM428.FCTJ.655"	"Error"
"HBM932.NDPL.855"	"New"	"HBM343.SWZV.994"	"Error"
"HBM946.LXHD.342"	"New"	"HBM957.NZZF.862"	"Error"
"HBM693.TKSR.989"	"New"	"HBM258.PBVL.874"	"Error"
"HBM325.NFQN.958"	"New"	"HBM749.GDWW.698"	"Error"
"HBM846.GNFK.382"	"New"	"HBM359.RDNH.724"	"Error"
"HBM826.JWQZ.557"	"New"	"HBM277.WPRB.277"	"Error"
"HBM498.GZWT.752"	"New"	"HBM577.FZTG.357"	"Error"
"HBM554.FXRG.494"	"New"	"HBM274.JZBC.499"	"Error"
"HBM554.FXRG.494"	"New"	"HBM894.JSZG.933"	"Error"
"HBM827.MTPX.728"	"New"	"HBM883.XVPB.363"	"Error"
"HBM828.MQHS.633"	"New"	"HBM538.KWLQ.343"	"Error"
"HBM286.BTKN.227"	"New"	"HBM578.BPWC.352"	"Error"
"HBM635.BVKS.668"	"New"	"HBM569.MGWP.595"	"Error"
"HBM998.SRDK.623"	"New"	"HBM563.WZNS.796"	"Error"
"HBM374.LXZR.573"	"New"	"HBM697.NHWT.586"	"Error"
"HBM359.TNQB.955"	"New"	"HBM768.DPJW.762"	"Error"
"HBM796.MHMH.858"	"New"	"HBM338.TWMK.388"	"Error"
"HBM532.BHTS.856"	"New"	"HBM644.FMMQ.355"	"Error"
"HBM293.WGGB.527"	"New"	"HBM282.CPCL.237"	"Error"
"HBM359.WSTS.688"	"New"	"HBM677.PDZZ.373"	"Error"
"HBM922.GQCQ.878"	"New"	"HBM689.BRLJ.478"	"Error"
"HBM828.CWHW.846"	"New"	"HBM224.KJRP.363"	"Error"
"HBM654.JKBH.876"	"New"	"HBM444.DXTZ.962"	"Error"
"HBM436.MSWB.224"	"QA"	"HBM935.GXNP.963"	"QA"
"HBM436.MSWB.224"	"QA"	"HBM957.LBVT.224"	"QA"
"HBM783.GTZQ.328"	"QA"	"HBM849.KCSB.536"	"QA"
"HBM979.DRXV.239"	"QA"	"HBM839.ZFRD.789"	"QA"
"HBM266.VHFM.835"	"QA"	"HBM523.BXZM.965"	"QA"
"HBM356.HJJX.599"	"QA"	"HBM685.MSCQ.978"	"QA"
"HBM329.LFSX.674"	"QA"	"HBM876.ZBTD.373"	"QA"
"HBM329.LFSX.674"	"QA"	"HBM249.BHHN.863"	"QA"
"HBM947.LJKB.895"	"QA"	"HBM265.NQCH.947"	"QA"
"HBM342.FWKM.533"	"QA"	"HBM536.FHLK.529"	"QA"
"HBM688.VFBR.562"	"QA"	"HBM388.BLRJ.658"	"QA"

**Comment by bhonick** [comment]
@shirey Thanks for notifying me about this: I was in error. Of the ones that are marked QA, only this pair should be deleted as they have been superseded by another: "HBM436.MSWB.224" "QA" "HBM957.LBVT.224" "QA"

Thus, the new list of datasets to be deleted is the following:
ds.hubmap_id ds.status processed.hubmap_id processed.status
"HBM569.GNMW.442" "New" "HBM929.MWVM.268" "Error"
"HBM569.GNMW.442" "New" "HBM382.VPBX.866" "Error"
"HBM564.VFQF.445" "New" "HBM836.GLRK.587" "Error"
"HBM286.SXPW.464" "New" "HBM925.HRDD.244" "Error"
"HBM443.PTSG.997" "New" "HBM657.STHT.488" "Error"
"HBM752.MJJP.255" "New" "HBM428.FCTJ.655" "Error"
"HBM932.NDPL.855" "New" "HBM343.SWZV.994" "Error"
"HBM946.LXHD.342" "New" "HBM957.NZZF.862" "Error"
"HBM693.TKSR.989" "New" "HBM258.PBVL.874" "Error"
"HBM325.NFQN.958" "New" "HBM749.GDWW.698" "Error"
"HBM846.GNFK.382" "New" "HBM359.RDNH.724" "Error"
"HBM826.JWQZ.557" "New" "HBM277.WPRB.277" "Error"
"HBM498.GZWT.752" "New" "HBM577.FZTG.357" "Error"
"HBM554.FXRG.494" "New" "HBM274.JZBC.499" "Error"
"HBM554.FXRG.494" "New" "HBM894.JSZG.933" "Error"
"HBM827.MTPX.728" "New" "HBM883.XVPB.363" "Error"
"HBM828.MQHS.633" "New" "HBM538.KWLQ.343" "Error"
"HBM286.BTKN.227" "New" "HBM578.BPWC.352" "Error"
"HBM635.BVKS.668" "New" "HBM569.MGWP.595" "Error"
"HBM998.SRDK.623" "New" "HBM563.WZNS.796" "Error"
"HBM374.LXZR.573" "New" "HBM697.NHWT.586" "Error"
"HBM359.TNQB.955" "New" "HBM768.DPJW.762" "Error"
"HBM796.MHMH.858" "New" "HBM338.TWMK.388" "Error"
"HBM532.BHTS.856" "New" "HBM644.FMMQ.355" "Error"
"HBM293.WGGB.527" "New" "HBM282.CPCL.237" "Error"
"HBM359.WSTS.688" "New" "HBM677.PDZZ.373" "Error"
"HBM922.GQCQ.878" "New" "HBM689.BRLJ.478" "Error"
"HBM828.CWHW.846" "New" "HBM224.KJRP.363" "Error"
"HBM654.JKBH.876" "New" "HBM444.DXTZ.962" "Error"
"HBM436.MSWB.224" "QA" "HBM957.LBVT.224" "QA"

**Comment by shirey** [comment]
@bhonick Primary dataset `HBM436.MSWB.224`, which you've listed for deletion has a second derived/processed dataset associated with it which is not listed for deletion, `HBM935.GXNP.963` should either:

  derived dataset `HBM935.GXNP.963` be deleted?
    or
  primary dataset `HBM436.MSWB.224` NOT be deleted?

**Comment by bhonick** [comment]
Neither HBM935.GXNP.963 nor HBM436.MSWB.224 should be deleted
