### ISSUE TITLE
Mint DOIs for IU CCF release

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#151]
Please mint the DOIs for the attached XML file per an email to Bill from Ellen on December 13, 2022 at 12:20 PM.

```
Hi Bill

Attached is a .zip of 45 xml files for use to DOI register the 4th release CCF files.

I had provided a .xlsx a while back to obtain HuBMAP IDs and the file names have now been harmonized with a GitHub naming schema and I found 1 file name that replicated a different name.

I assume that list will be superseded by the actual xml files and the reference-entity-ids.tsv that resides in the ccs-releases Github repository.

Let us know if there’s any problems.

When do you think this can be scheduled to get these DOIs live for the CCF/HRA portal on our side?

Thanks a lot, 

Ellen
```
[xml-ccf-4threlease.zip](https://github.com/hubmapconsortium/manual-data-ingest/files/10345487/xml-ccf-4threlease.zip)

**Comment by yuanzhou** [comment]
Conflict found. I created DOI based on `omap-2-intestine-codex.xml` first, then noticed that the `omap-3-kidney-codex.xml` uses the same HuBMAP ID `HBM794.CSBJ.358` and it's an invalid XML file with syntax error. The DOI system doesn't allow duplicate ID.

**Comment by emquardokus** [comment]
@yuanzhou Thanks! Let me track this down; will get back to you.

**Comment by emquardokus** [comment]
[omap-3-kidney-codex.xml.zip](https://github.com/hubmapconsortium/manual-data-ingest/files/10352973/omap-3-kidney-codex.xml.zip)
@yuanzhou Attached is a .zip of the new xml file for kidney; the omap-3-kidney-codex.xml had been incorrect in first batch. 
Thank-you
Ellen

**Comment by yuanzhou** [comment]
Thanks for the fix @emquardokus. I've published the 45 DOIs.
