### ISSUE TITLE
Datasets `HBM347.RFGL.437` and `HBM773.WCXC.264` are missing metadata

### ISSUE THREAD

**Issue by icaoberg** [hubmapconsortium/manual-data-ingest#152]
The datasets above are missing the metadata associated with the metadata file. 

Even though these datasets have been ingested and a metadata.tsv file is present, it seems we did not ingest the file it self, so there are no references of the fields in the TSV present in the database.

For reference, these are public protected datasets from UCSD.

@pdblood I manually resolve the issue in code for the dbGaP submission.

**Comment by shirey** [comment]
@icaoberg or @bhonick I'll need the correct metadata associated with the dataset ids to update this.
