### ISSUE TITLE
Collection and DOI for Stanford RTI MIBI data

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#174]
Create a collection and DOI based on the attached files.
[Collection Form (Final) (Responses).xlsx](https://github.com/hubmapconsortium/manual-data-ingest/files/11032722/Collection.Form.Final.Responses.xlsx)

[contributors - Sricharan Reddy Varra.tsv.txt](https://github.com/hubmapconsortium/manual-data-ingest/files/11032729/contributors.-.Sricharan.Reddy.Varra.tsv.txt)

**Comment by shirey** [comment]
@yuanzhou I created the collection, assigning to you to create a DOI, but let me know what I can do to help.
  uuid: `3ae4ddfc175d768af5526a010bfe95aa`
  hubmap_id: `HBM585.QPDV.454`
  
  We'll need to fill in the `doi_url` and `registered_doi` fields after the DOI has been created.

**Comment by yuanzhou** [comment]
@shirey I've noticed the same ORCID 0000-0002-8460-8229 being used by many creators from the entity-api result `https://entity.api.hubmapconsortium.org/collections/3ae4ddfc175d768af5526a010bfe95aa`.

**Comment by JAH386** [comment]
@yuanzhou reached out to Stanford contact to rectify.

**Comment by yuanzhou** [comment]
Thanks @JAH386. I'll see if I can add them without using Orcid IDs. Otherwise they will have to create their Orcid IDs or we may not be able to include them. But I'll first see if it's required.

**Comment by JAH386** [comment]
[contributors Stanford MIBI updated.odt](https://github.com/hubmapconsortium/manual-data-ingest/files/11192679/contributors.Stanford.MIBI.updated.odt)

Updated tsv without the missing Orcid ID info.

**Comment by shirey** [comment]
@yuanzhou I've updated the database with the new contributor (`Collection.creators`) information.

**Comment by yuanzhou** [comment]
DOI created and indexed into OpenSearch too, https://doi.org/10.35079/hbm585.qpdv.454
