### ISSUE TITLE
20230404: Deletion of Derived Datasets - snRNAseq, TMC-Stanford

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/manual-data-ingest#175]
Hi @shirey , the following derived datasets can be deleted. Thanks!

HBM555.NTTQ.244
HBM279.PKFV.427
HBM449.KZJM.346
HBM223.NPBD.879
HBM887.WLBV.234
HBM549.XDHD.689
HBM769.KGPQ.395
HBM932.XRHF.586
HBM532.CWWB.393
HBM725.SRKT.739
HBM857.CTTG.929
HBM646.LJTN.264
HBM386.SPNZ.359
HBM535.SDKT.567
HBM356.LQPG.863
HBM587.MWHM.794
HBM488.WNGR.837
HBM626.JNSV.978
HBM378.XSWZ.697
HBM752.RVMR.747
HBM294.XJZN.322
HBM339.TMHM.678
HBM439.HHFR.332
HBM659.BPGZ.286
HBM498.DSDQ.473
HBM465.MGFF.748
HBM638.GQQT.629
HBM357.QBXH.549
HBM389.LPTN.385
HBM839.RVCS.795
HBM443.BFCX.679
HBM625.GFML.462
HBM249.BHHN.863
HBM957.LBVT.224

**Comment by bhonick** [comment]
@shirey The QA primary and derived datasets below can be delete. The data provider has indicated that they have not used this dataset.

HBM394.XZQH.989
HBM924.RFFJ.887

**Comment by bhonick** [comment]
@shirey Adding three MIBI from RTI-Stanford that are all in error:

HBM982.MCCD.883
HBM847.QRBL.245
HBM562.TGRW.584

**Comment by shirey** [comment]
Closing this.

@bhonick All have been deleted EXCEPT `HBM436.MSWB.224`  which has a second derived dataset, `HBM957.LBVT.224` attached to it that isn't listed for deletion.  I did delete `HBM935.GXNP.963` which was also attached to `HBM436.MSWB.224` and listed for deletion.  Let me know in a separate issue if both `HBM436.MSWB.224` and `HBM957.LBVT.224` should be deleted.
