### ISSUE TITLE
API Gateway for User Templates API

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#185]
Create the definitions and implementation in the AWS API Gateway for the User Templates API
@jpuerto-psc Any additional information/links to specs appreciated..

**Comment by jpuerto-psc** [comment]
API docs: https://smart-api.info/ui/1607c43d6b0f22cc2ba5599c7f1e5219
Base URL for DEV: user-templates-api.dev.hubmapconsortium.org
