### ISSUE TITLE
Publish UFL Codex

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#187]
Per email from Diane on 4/18/2023 at 9:07 AM publish the attached.
[TMC Florida _ CODEX _ QA_20230412.xlsx](https://github.com/hubmapconsortium/manual-data-ingest/files/11267366/TMC.Florida._.CODEX._.QA_20230412.xlsx)

Primary   Dataset | Derived Dataset
-- | --
HBM927.KDXB.445 | HBM435.FHMP.758
HBM723.BZKF.992 | HBM332.QJCH.296

**Comment by shirey** [comment]
@bhonick @diane-psc Dataset HBM927.KDXB.445 is in the New status.  We require it to be in QA for publication.

**Comment by bhonick** [comment]
I've asked Sunset to update the status. I'll let you know when I hear back.

**Comment by bhonick** [comment]
HBM927.KDXB.445 now is in the QA status.

**Comment by shirey** [comment]
@diane-psc These have been published
