### ISSUE TITLE
Delete bad UCSD derived datasets

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/manual-data-ingest#19]
HBM372.NNLG.822
HBM484.DCSH.228
HBM562.NBVJ.465
HBM338.GSSL.872
HBM255.FMPB.664
HBM735.KXMM.334
HBM268.LLCK.854
HBM378.FXDJ.698
HBM865.LWLC.946
HBM978.JLVM.579
HBM865.VNHM.356
HBM866.DVLJ.653
HBM788.XJNW.947
HBM985.JMLQ.489
HBM545.KVMD.667
HBM346.ZBRG.722
HBM294.CLBL.794
HBM687.SDTL.672
HBM343.SNLG.353
HBM679.TZGD.227
HBM426.FNGM.757
HBM999.QDCK.462
HBM985.LBWX.655
HBM393.BZZK.482
HBM822.MRXJ.635
HBM374.QWNX.564
HBM578.XVCJ.669
HBM329.FFKW.785
HBM527.TVTF.823
HBM598.XMVL.794
HBM549.LJJJ.295
HBM566.QKPD.732
HBM327.TMTJ.849
HBM277.XLXB.696
HBM428.GLNT.622
HBM247.TKXW.894
HBM845.HPWN.396
HBM489.QPGP.465
HBM266.NHCB.624
HBM739.RCRM.678
HBM742.BPZN.895
HBM238.DDRL.349
HBM485.VSJV.684
HBM857.HDNT.433
HBM549.CVNZ.448
HBM667.GWWL.447
HBM769.QLBW.479
HBM658.TDBS.922
HBM883.WHZZ.548
HBM462.TRSJ.255
HBM995.ZWNJ.624
HBM423.GDCS.532
HBM586.JCKQ.376
HBM827.LGBZ.593
HBM943.DWRB.362
HBM987.LLRL.246
HBM377.JJHK.449
HBM846.MVNR.339
HBM345.TNVQ.666
HBM483.RWCW.455
HBM937.WLZW.669
HBM639.ZTSG.226
HBM332.TTKD.825
HBM964.NVDK.793
HBM525.DNJD.833
HBM222.ZXZM.366
HBM965.TSLJ.667
HBM357.JKWH.436
HBM394.QHSM.987
HBM389.VPWS.365

**Comment by khanshawPSC** [comment]
HBM662.XPDF.848

**Comment by shirey** [comment]
All except  "HBM222.ZXZM.366" and "HBM294.CLBL.794" have been deleted
@khanshawPSC Can you confirm that these two should be deleted?  The others were deleted as part of another issue from Joel, I believe.

**Comment by shirey** [comment]
I deleted the remaining two mentioned above.
