### ISSUE TITLE
Publish TMC-Stanford | RNA-seq | 20220802

### ISSUE THREAD

**Issue by diane-psc** [hubmapconsortium/manual-data-ingest#193]
On 8/2/22, Annika approved the processed dataset HBM893.JVLB.845 to publish. However, it is still in QA. This is supposed to go with the raw dataset HBM945.QNRF.244 which is published.

Could you please publish HBM893.JVLB.845?

[Per email sent on 8/2/2022, subject: Reprocessed RNA-seq]

**Comment by shirey** [comment]
@diane-psc HBM893.JVLB.845 has been published
@bhonick The following datasets are also attached to HBM945.QNRF.244 as dervived/processed datasets, let me know if they should be deleted (I'm closing this issue, so open a new issue for delete if needed)
```
"HBM942.XLHP.469"	"QA"
"HBM262.NJQZ.634"	"Processing"
"HBM526.BXJR.935"	"Error"
"HBM656.TJNG.945"	"QA"
```
