### ISSUE TITLE
Populate the Portal with Cal Tech's dbGaP dataset link

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/manual-data-ingest#202]
Requested by Phil, for dataset `HBM666.FFFW.363` (https://portal.hubmapconsortium.org/browse/dataset/d926c41ac08f3c2ba5e61eec83e90b0c), add `dbgap_sra_experiment_url` and `dbgap_study_url` based on the google doc (https://docs.google.com/document/d/1G9fbj19u0YoMK1dzbRxP77FjWsMiay9qfKYYS5Z9RRE/edit) and spreadsheet info. 

<img width="565" alt="Screenshot 2023-05-23 at 10 50 05 AM" src="https://github.com/hubmapconsortium/manual-data-ingest/assets/195873/b31c1952-03a2-4028-92da-aa6e1e8820f0">

Tested on TEST:
```
dbgap_sra_experiment_url = https://ncbi.nlm.nih.gov/sra/SRX13283313
sra experiment id = SRX13283313
dbgap_study_url = https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs002267
dbgap study id = phs002267
```

**Comment by shirey** [comment]
@yuanzhou Please set those two URLs in production then respond on Slack.

**Comment by yuanzhou** [comment]
FYI @shirey, new fields added on PROD for dataset `d926c41ac08f3c2ba5e61eec83e90b0c`:
```
"dbgap_sra_experiment_url": "https://ncbi.nlm.nih.gov/sra/SRX13283313"
"dbgap_study_url": "https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs002267"
```
