### ISSUE TITLE
Publish CalTech | RNAseq| reprocessing datasets

### ISSUE THREAD

**Issue by diane-psc** [hubmapconsortium/manual-data-ingest#204]
[Datasets](https://docs.google.com/spreadsheets/d/1bWKDl-RINuG82k_G1uuEu90MvkLHX9ktKfCF2xvqVz4/edit#gid=2086697513)

Please publish just the derived datasets

**Comment by shirey** [comment]
@bhonick Please confirm:

These are the datasets that need to be versioned, new version --> old version

```
new_derived	                 old_derived
"HBM342.CMHT.948" ["HBM276.ZCGM.239"]
"HBM385.LQVK.975"	["HBM726.SGLJ.852"]
"HBM927.DZCV.762"	["HBM888.CHTX.783"]
"HBM852.VXGN.375"	["HBM284.MNHF.223"]
"HBM599.GNJN.777"	["HBM599.WCGN.978"]
"HBM982.THGM.772" ["HBM255.QMNS.733"]
```

**Comment by bhonick** [comment]
@shirey I approve of these linkages, thank you.

**Comment by shirey** [comment]
@bhonick @diane-psc These have been published.
