### ISSUE TITLE
Publish TMC-Stanford | RNAseq-10xGenomics | Reprocessing

### ISSUE THREAD

**Issue by diane-psc** [hubmapconsortium/manual-data-ingest#206]
Publish the derived datasets.

[Spreadsheet](https://docs.google.com/spreadsheets/d/1aWYcdJxhKcJl44A1h4pKkau30YOJuNBHZt57xX6u8og/edit#gid=2086697513)

**Comment by shirey** [comment]
@bhonick Please confirm:

These are the linkages for new version -> old version:
```
new_derived	                old_derived
"HBM236.JPVT.769"	["HBM893.JVLB.845"]
"HBM537.MVDQ.934"	["HBM949.ZHRT.229"]
"HBM957.TXXZ.387"	["HBM877.JFMS.222"]
```

**Comment by bhonick** [comment]
@shirey I approve of these derived dataset linkages, thank you. Additionally, the primary datasets listed with "Do Not Publish" are already in the `Published` stage, so they do not require further action.

**Comment by shirey** [comment]
@bhonick @diane-psc These have been published
