### ISSUE TITLE
Publish Stanford | LC-MS | 20211108

### ISSUE THREAD

**Issue by diane-psc** [hubmapconsortium/manual-data-ingest#212]
Please publish 128 primary datasets.

[TMC-Stanford _ LC-MS _ 20211108 (1).xlsx](https://github.com/hubmapconsortium/manual-data-ingest/files/11709025/TMC-Stanford._.LC-MS._.20211108.1.xlsx)

**Comment by shirey** [comment]
@diane-psc These have been published
