### ISSUE TITLE
Create review list for UCSD snareSEQ data

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/manual-data-ingest#35]
Please create the list for these datasets from UCSD:
HBM783.ZJCH.496
HBM977.LLMG.325
HBM859.HQTC.955
HBM538.ZGLW.939
HBM888.MQJH.424

So we can send it to Blue for review.

**Comment by shirey** [comment]
@khanshawPSC Was this done?  Hoping it was... *yikes*
