### ISSUE TITLE
Add a dataset to IU's current project directory with GE and edit permission

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/manual-data-ingest#37]
The dataset is currently here: https://drive.google.com/file/d/1VUww8Y_KpiIuGlggmD5kETNhVSm3wsfc/view?usp=sharing

And we would like for it to be put on Globus to:
HuBMAP Data/projects/ [new folder] MC-IU/GE_skin_data

Andreas Bueckle and Yingnan Ju would like read/write access to the directory also.
yiju@iu.edu
abueckle@iu.edu

**Comment by shirey** [comment]
Directory created at: https://app.globus.org/file-manager?origin_id=24c2ee95-146d-4513-a1b3-ac0bfdb7856f&origin_path=%2Fprojects%2Fge-skin-data-for-iu%2F

I don't have read permissions on the Google folder so can't copy the data from Google.
