### ISSUE TITLE
More uuids to prune

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/manual-data-ingest#48]
Please delete the following UUIDs from PROD when possible.  The reasons given are just for my reference.

0211f75d7820d4edb3ae1f34323884c5 (re-run parent now that sc-atac-seq #35 fixed)
1aeff8448ec254f65f00ad999f6b95a7 (same as above)
f57dc190a6b8b1ebf29a3faf07a5b90b (same as above)
7779aff375ee3236811e38375e70b2c7 (failed Slide-seq; thinks it's 10X)
8c9b0ca0fa786e9ed6e4b875303246e6 (failed salmon_rnaseq_slideseq)
da7ad48d39a98603336cfa7c03dd6c96 (failed CODEX run)
31c75504244df603355102cff4b73d6c (failed multi ATAC)
cb22b7da3c456837e891465b03e4cff5 (failed multi ATAC)
509b3821bc940d995565adcadbfa83e6 (failed multi ATAC)
482e677b1d4617cc056f99631cb93b66 (failed multi ATAC)
129a1af0945329917a8bb20aacd561c4 (failed multi ATAC)
ea384ce4df06b77bf9ce130cdf4a7335 (failed multi ATAC)
9a96490967e7b5e4f33bb8ba152e2779 (failed multi ATAC)
987ff64aeefaeca62568334aa94a9a58 (failed multi ATAC)
735687fc65e9b3a033334c9c0caffee3 (failed multi ATAC)
f8b63c64435fc6ad3bf8530faec8e9ad (failed multi ATAC)
c6d668e081c9fdbdf6f927996ec1cf58 (failed multi ATAC)
27ec8e368d3e5427f1f9d5015676ad24 (failed multi ATAC)
a51870fde54152df2cad6a98ddcd0b34 (failed multi ATAC)
36538f96467725031b5fd5eee2e95d98 (failed multi ATAC)
060a6d6b7c1aca10612f38f66892da14 (failed multi ATAC)
d4a25576341fde5a8fd81e26b097ab06 (failed multi ATAC)
b5d7cb1e27afa0c97808984d48a8d5b4 (failed multi ATAC)
ea384ce4df06b77bf9ce130cdf4a7335 (failed multi ATAC)
6a8caf69499761916cee5af4bc805cf6 (failed multi ATAC)
394d43f79e18422b481b35f66218b940 (failed multi ATAC)
a5ea8d8119cbc6523670fdd31fefd125 (failed multi ATAC)
9ffc58662afa201b7bfcce96f6aed6eb (failed multi ATAC)
9dd9a7f67a819ba3939c01bd97356dd3 (redundant multi ATAC)

**Comment by shirey** [comment]
@jswelling These have been deleted
