### ISSUE TITLE
More uuids to prune (Nov 2021)

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/manual-data-ingest#52]
Please delete the following uuids from PROD.  They are CODEX derived datasets run with an obsolete SPRM.

373a1954f1dc042ef661dfd41638baa1 | HBM944.QMKZ.368
615325b3d41e698a10b66f7b5a5b0dde | HBM836.GQLB.948
93c4baa434f0ed3691ce5b2d20ee1460 | HBM747.VMTC.265
36cdaaa6f0b1fcfba152ae8ce7d8743b | HBM529.FVVK.339
8910d76c8db5cc313770871915000dcd | HBM996.GJWS.674
0818d99b029867ab106c2bafaf5aac1d | HBM523.SPQL.468
dd6aad7ff7392a08c758f8293c2d233b | HBM672.KTMB.447
684f58929973a6462acf0c1f30904ead | HBM489.HJRT.839
831a135b6d08757cc5c034b826898b4b | HBM938.WTDN.856
3eb9accab20e1b11c369375c0914a9bd | HBM746.LXCC.432
a5813ea23a51ab371fec01bea24455b1 | HBM543.CZST.823
ecdfcb5fe4264c5373823cd99a3a6c4b | HBM696.TMHL.935
a02ffcb8952ec94f8364aa5c485bc56b | HBM233.WJKX.732
26ded5fe25da9b90693f6cd354977645 | HBM739.GGRW.728
69b740f4477c5597d9e8600bf2c10986 | HBM578.PTCL.883
7bf4abe06284a072924c9e3faa2e54f3 | HBM332.TBTM.697
8bf859e19360761b4720c168517589b3 | HBM565.NKZC.973
bd86575f5100b4814fc2f9db4be03e1e | HBM347.JNLB.837
094b3c5d797d1058dbe7585082c32bc1 | HBM284.VTXV.694
1bea8077006cd5da6e5c1ec892bc4f83 | HBM548.GWWF.537
874089a6f97daa2ca99cf0fc79b01d96 | HBM658.KZML.833
ab1dbe2f10a38a2da74a8ffed99ac9d6 | HBM673.HZZC.792
2804c6782b915a31b129ad51535b2317 | HBM666.XKPB.244
2db9ee68762ac8df78a649a575964201 | HBM238.PLDB.795
2e73a4b318798265cfe845f32776abb3 | HBM685.FJHS.737
a1170f14cd32e00255c869b47b66ea80 | HBM938.ZBTF.576
d3708cdecb44892786e9b17ca560a065 | HBM858.RJFH.757
0c33f3bfaed32f94a9f12c1b40a48e92 | HBM446.XDZM.849
c6dced4f4d1ab1135ea2ce5769812f84 | HBM934.HCLQ.487
eb4f29d80fde45b867278879b3eeb55c | HBM479.JNRW.327
077a148008ec97f71c23804327e9ed29 | HBM247.MDTP.826
b4751320eff96645950478a51b8f5c2e | HBM622.FVXZ.748
d046489ec392865cd7e0039eade3646c | HBM589.VJQJ.326
d6585307bdd7e619910ef92c0fe51921 | HBM445.ZHCG.875

**Comment by jswelling** [comment]
Please also remove b916668d4d0f5ca7034a134d61eb719f (failed codex_cytokit run)

**Comment by jswelling** [comment]
Please also remove the following 3 uuids:
* 98a31323f57f9d06b013c95718b59823 (failed SNARE-seq2)
* c10ef3519a4bc1cdcf955757160865fe (failed codex_cytokit)
* 90410df25e04ddb177f01935c949beb1 (failed codex_cytokit)

**Comment by shirey** [comment]
All deleted from PROD
