### ISSUE TITLE
More uuids to prune (Jan 2022)

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/manual-data-ingest#56]
Please delete the datasets with the following uuids from PROD.

abd1d80822592d0e718a17d634910438  (bad codex-cytokit)
434b3113387d59fc19f65c2e5895ae4e (bad CellDIVE)
0c98ea4959b6e435ac3ac04b93465337 (bad CellDIVE)
65e89aeae5df1f2fcc534cdc6812bd61 (bad CellDIVE)
42b148c1b42b10d0b8bef371b42d48da (bad CellDIVE)
074fee6710c1622139d2ff00431c534c (bad sc_atac_seq_snare)
5257f7e4790359eddf367b6e0f1cb477 (bad sc_atac_seq_snare)
e710a1bf3773092f0ac2365de0fa8b39 (bad sc_atac_seq_snare)
009712bb284b0291247037c46511ce00 (bad sc_atac_seq_sci)
5487988e85b165d6ad3cab1bef1067d2 (bad sc_atac_seq_sci)
d6e4c234015d11a24b8a4a79376404b0 (accidentally launched sc_atac_seq_sci)
3c97dbd44ba989c41c29cd2687311366 (salmon_rnaseq_sciseq replaced by newer version)
59cbc103a6ab0e9d55a8b4b47e3e25b0 (salmon_rnaseq_sciseq replace by newer version)
d3a399c31a0f9d8bad4294691d2c8f35 (salmon_rnaseq_sciseq replaced by newer version)
600325157b07f4ec34ab98bcec1f1867 (salmon_rnaseq_sciseq replaced by newer version)
92436cee1b8037a1b191a01546c3802c (salmon_rnaseq_sciseq replaced by newer version)
b513c806bf3ee0d43d7ee6080d49913d (salmon_rnaseq_sciseq replaced by newer version)
f6b6f4b613ef675eae82e9a00684228a (salmon_rnaseq_sciseq replaced by newer version)
a54cf3c7d138abbbdb68de06da83f711 (salmon_rnaseq_sciseq redundant copy)
ae8847ddd48cd1d9c96dc1e6f6c259d1 (salmon_rnaseq_sciseq replaced by newer version)
0bb7731a301114bf2d9336d4979ed31f (salmon_rnaseq_sciseq replaced by newer version)
e39662494e4dc66a3decc52e412b6552 (salmon_rnaseq_sciseq replaced by newer version)
d4e85897ce6037c09b7d3a4de9a7205a (salmon_rnaseq_sciseq replaced by newer version)

**Comment by jswelling** [comment]
Please also delete:

d6ec9ff2219e8cb74e807ded7e35c25e (salmon_rnaseq_sciseq replaced by newer version)

**Comment by shirey** [comment]
These have been deleted.
