### ISSUE TITLE
Please change assay_type to SNARE2-RNAseq for these datasets

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/manual-data-ingest#57]
The following PROD QA datasets are incorrectly marked as sciRNAseq in the database.  Please change them to assay_type SNARE2-RNAseq .  I have already updated the metadata.tsv files to the correct string in place.

01160f557b3544a163184137530ededf
015ee234392256bfdb315299622ccb87
055944e2ee7579974aa7a2a11dff5637
0dad96d381eab1a598b76038385e593f
12adb09fef9ef119227ecbe87b41dcc2
154ec6344a58e4acb15ad01977b84baf
155da15afc9978b62d64bf0801d025dc
19274e67c639a003ffe17953fd6b55db
19be408fb97c09f603c906921d7b0945
1bb63db033b3f7206a4d8c4ac4db1564
21cfe966008f784c47d0638e80b55ee0
2746ce8d450265ace2c6aee762c8dfda
397b6f876ec7976923650135481d08e5
421007293469db7b528ce6478c00348d
4318b88da67256edae9fd876b5111e4a
43f83f08bedac2bc4d58767362dfebe2
4ea28b66fb08185a484df0fa0b9543dc
500af39b83bfa9eb27f78746734f3db9
59da4436e52d9cacc743c1a9bbdd566f
614073f249f8881b2fe4a29db6bea266
670135e38ac4107e0d07dae1bdcf4936
6f87add44880de684e6a9a5625344bbb
76584f2fe8e8ec215d78b83296461bbf
7e452891b83ca984a2f210312d90495d
83886790424cd10f6b50159ef50555ed
8464b72f60b42590266834f9049055f4
869ff5b556a0e0f24a48aa673d0bc343
88a335560ab0bc16c7d63c01d6480f3d
96c782b502cdb23122b2e7fb376d949d
9b64312cac3c359e0fef53555057c996
ade674f0277942c9a1297494fcf3511d
c5e4adcf2ef956864a087d1691e8e8cd
c820345b025ff959e531db797030a399
c858b21d7bbfbe4e73d9f72c2c719c62
d2514a9f220952cf2dd75796206eeb11
d2f1ba23eddf1484f4a794444a6536ee
d34706323794467348995af37072b5ee
d34eb3a317ac17d6f01b958cb2276793
d615cc96a8606bb6819bed2a8d7f24ac
d68eb55a484036b3575043bdecd64a52
d7bd2925c466eedc009c1cd272011529
d91f01da45d9011b702cbff221c0ddeb
da37b64d6f5823747274c719cd590890
de80a443ed15e1f783c68d5e0b2d7216
df71091620312eacc28a6accccfb2aa4
e8efba8d06360eeba199f195da80f01d
eea962dabda0cec78f8f909494e0e775
efe5894cd09b0a411ecfe46749e6db73
f41e71ec9619dbb065634b4714d1818e
f852d653926edb68292e39b95a3469cf
1c9310ad74bdebc6983fb1bda3dcaa6e
324e4aa3c65fd6644234bbfd61b358de
5f13e1e3140b58650018ec44ecad720c
79e94dcf00267a0fe71e88c7d1e8d3c8
9c059f193bb4db45250e3b5eb303eaf4
f4333f83c8aadb7ea132844e7d0097fb

**Comment by shirey** [comment]
The data_type code has been changed in these datasets to `SNARE-RNAseq2` (the primary specified code in assay_types.yaml) vs the above specified code, `SNARE2-RNAseq` which is an alternate code.
