### ISSUE TITLE
Delete UCSD SNARE Hold datasets

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/manual-data-ingest#64]
Please delete UCSD datasets in Hold status below:
HBM874.KHKH.889

HBM679.DRJV.822

HBM934.ZGDF.266

HBM233.DXLM.923

HBM958.MTZX.874

HBM983.BZFG.839

HBM697.DCBR.894

HBM656.PGLB.667

HBM777.CNRD.787

HBM535.DNDR.477

HBM735.QRQS.997

HBM855.HVVZ.582

HBM929.XWLH.575

HBM969.XTPP.352

HBM544.RVLT.964

HBM369.KBTP.935

HBM759.GLXZ.545

HBM495.BLDC.993

HBM827.WTDW.339

HBM437.LLQK.923

HBM283.ZBLB.947

HBM799.RNNX.544

HBM843.BVPC.439

HBM793.LLWK.926

HBM283.TSZC.443

**Comment by shirey** [comment]
Deleted
