### ISSUE TITLE
Weekly AirFlow run to update Globus usage json

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/manual-data-ingest#94]
Install the script created in [Globus transfer usage json task](https://github.com/hubmapconsortium/manual-data-ingest/issues/93) for a weekly AirFlow run.

Use the following inputs:
  - Secret application (non-Globus, Joel knows this and it should be internally available in AirFlow runs) token
  - The usage .csv file from the file `/hive/hubmap/data/usage-reports/Globus_Usage_Transfer_Detail.csv`
  - The gridftp-audit logs from the directory `/hive/users/backups/app001/var/log/gridftp-audit/`

Output json to:
  - `/hive/hubmap/assets/usage/globus-data-transfers.json`

The input to the python script should include the latest transfer_usage.csv from Globus and all Globus audit log files.

The output should be directed under the `/assets/` directory where it will be accessible via the assets service

**Comment by DerekFurstPitt** [comment]
Talk to joe to make sure that the json file will be available through the asset service. @yuanzhou

**Comment by jswelling** [comment]
The output seems to be a single filename.  Is the intention to replace that file once a week, or append to the file over time?

**Comment by DerekFurstPitt** [comment]
@jswelling It will be replaced
