### ISSUE TITLE
UUIDs to prune May 2022

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/manual-data-ingest#96]
Please delete the following datasets.  Reasons given are for tracking purposes only.

314619099eaf7cb8966d9168b8995a63   - Error state from failed salmon_sn_rnaseq_10x
7f4da1520b105e31f4679c4680e5e5cf - Error state from failed salmon_sn_rnaseq_10x
f9670074e07212a6fcc3f27a621b7f1e - Error state from failed salmon_sn_rnaseq_10x

**Comment by jswelling** [comment]
Please also delete the following:

397d96e65da5a46d127d6ca2be05051d - failed CODEX 5/9/2022
1fb5a496e0d918d58b1cb1a430897f06 - failed CODEX 5/9/2022
a8d675808fe307bb7ecd3746939a9a43 - failed CODEX 5/9/2022
6973701cd9fa556d86d8469473b52d45 - failed CODEX 5/9/2022
8ee9884c788572f89d51d9db0d8a6058 - failed CODEX 5/9/2022
7e7afc3444edf41200c10823f8fab462 - failed CODEX 5/10/2022
6a39e8f355e59c5a333cbc78504621ec - failed CODEX 5/10/2022

**Comment by shirey** [comment]
Deleted 5/23/2022
