### ISSUE TITLE
Delete datasets

### ISSUE THREAD

**Issue by JAH386** [hubmapconsortium/manual-data-ingest#97]
Please delete the following Stanford snATAC-seq datasets below 

HBM957.DNGV.753
 
HBM963.CVMG.487
 
HBM768.RJWH.288
 
HBM869.NGJV.522
 
HBM895.XSZC.792
 
HBM336.GPWZ.529
 
HBM787.GCDK.358
 
HBM355.FFDZ.953
 
HBM356.GZSR.649
 
HBM698.HVKB.873
 
HBM772.VFNT.262
 
HBM872.WWGQ.534
 
HBM334.BGBM.423
 
HBM474.GLZD.683
 
HBM374.KHCN.564
 
HBM944.JXWG.952
 
HBM377.QVWQ.598
 
HBM655.QZSV.479
 
HBM673.LGJN.668
 
HBM928.KLFX.464
 
HBM435.FNRR.996
 
HBM625.BQGX.698
 
HBM677.PVSC.793
 
HBM754.DNFF.267
 
HBM249.QVXL.684
 
HBM957.LDZS.484
 
HBM287.SJQX.973
 
HBM859.QNSQ.452
 
HBM692.PQZQ.488
 
HBM232.KSPB.852
 
HBM498.VNPT.829
 
HBM575.JDSP.798

Also, please delete the following datasets currently in error status:

HBM933.GGZX.232

**Comment by shirey** [comment]
Top list from an email on 4/29/2022 @ 2:56PM from Peter approved by Matt in same thread on 5/11/2022 @ 12:12PM.

HBM933.GGZX.232 from an email on 5/11/2022 @ 12:56PM from Peter.

**Comment by shirey** [comment]
Deletes performed and data saved in folder: /hive/hubmap/data/deleted/5.19.2022/
